services:
  postgres:
    image: postgres:16
    container_name: churn_postgres
    environment:
      POSTGRES_USER: churn
      POSTGRES_PASSWORD: churn
      POSTGRES_DB: churn_warehouse
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U churn -d churn_warehouse"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:4
    container_name: churn_adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  metabase:
    image: metabase/metabase:v0.50.27
    container_name: churn_metabase
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - metabase_data:/metabase-data
    environment:
      MB_DB_FILE: /metabase-data/metabase.db

volumes:
  postgres_data:
  metabase_data:

