create table if not exists raw_customer_behavior (
    "Customer_ID" text,
    "Age" text,
    "Gender" text,
    "Country" text,
    "City" text,
    "Membership_Years" text,
    "Login_Frequency" text,
    "Session_Duration_Avg" text,
    "Pages_Per_Session" text,
    "Cart_Abandonment_Rate" text,
    "Wishlist_Items" text,
    "Total_Purchases" text,
    "Average_Order_Value" text,
    "Days_Since_Last_Purchase" text,
    "Discount_Usage_Rate" text,
    "Returns_Rate" text,
    "Email_Open_Rate" text,
    "Customer_Service_Calls" text,
    "Product_Reviews_Written" text,
    "Social_Media_Engagement_Score" text,
    "Mobile_App_Usage" text,
    "Payment_Method_Diversity" text,
    "Lifetime_Value" text,
    "Credit_Balance" text,
    "Signup_Quarter" text,
    "Churned" text
);

create table if not exists mart_churn_risk (
    customer_id text primary key,
    country text,
    city text,
    age_group text,
    engagement_score numeric,
    churn_risk_score numeric,
    risk_segment text,
    cart_abandonment_rate numeric,
    days_since_last_purchase numeric,
    customer_service_calls integer,
    estimated_revenue numeric,
    lifetime_value numeric,
    churned integer
);
